### ISSUE TITLE
OpenLCB: Missing PIP request after a repeated Initialization Complete message

### ISSUE THREAD

**Issue by heikens** [openlcb/OpenLCB_Java#10]
@balazsracz When starting a node from the bootloader and doing a firmware update, then at the end of a successful update an automatic transition happens to Operational state. In that transition, the bootloader releases its alias to allow the Tower-LCC to acquire a new alias, which ends with an Initialization Complete message. A SNIP request is issued - updating that piece of info about the node - but no PIP request, so a user is stuck with the residual items from the bootloader PIP, meaning no CDI support, no Event support, until restart of JMRI.

**Comment by balazsracz** [comment]
https://github.com/openlcb/OpenLCB_Java/pull/13 is the fix

**Comment by balazsracz** [comment]
fix merged
