### ISSUE TITLE
No Way to cleanly terminate threads

### ISSUE THREAD

**Issue by pabender** [openlcb/OpenLCB_Java#119]
This is primarily a testing issue, but when OpenLCB objects are created, there is no way to cleanly destroy the threads they leave behind.  We need to find a way to do this.

This was discovered while working on a JMRI issue ( https://github.com/JMRI/JMRI/pull/4818 ) where the JMRI test suite creates a very large number of OpenLCB related objects in testing its interfaces, but has no way to terminate the threads left behind.

**Comment by pabender** [comment]
This has been reduced sufficiently that this issue will be closed.  Most of the still open threads are waiting to be garbage collected when tests complete.

**Comment by dpharris** [comment]
Thank you for your work on this issue, and also to others for their input.


David
