### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#120]
In the draft TCP standard there are mDNS names set for automatically connecting to an OpenLCB network. We should have an implementation for this in openlcb.jar or downstream in JMRI.

**Comment by pabender** [comment]
JMRI has capabilities to advertise mDNS services already.  It will be pretty simple to add that.  I’ll try to review the relevant documentation for the names to use.

**Comment by balazsracz** [comment]
The name should be  _openlcb-can._tcp when the hub is running.
This is documented in the TcpStandard (not sure if it's the S or TN).

thanks
Balazs

**Comment by icklesteve** [comment]
Hi @balazsracz , can this be closed down?

The JMRI Hub Control should be advertising on `_openlcb-can._tcp.local.` ?
https://github.com/JMRI/JMRI/blob/master/java/src/jmri/jmrix/openlcb/swing/hub/HubPane.java#L211

Ta, Steve.

**Comment by bobjacobsen** [comment]
I confirm that JMRI is advertising as required.  This can be closed.
