### ISSUE TITLE
CDI editor: identification segment rendered with unexpected X offset

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#14]
Check the attached screenshot.
Taken with the Jenkins build of JMRI on Oct 31. (under linux ubuntu 64-bit) The identification segment is rendered in the CDI window with a strange x offset. It should be aligned to the left of the dialog.

@pabender  could you take a look at what might be causing this? 
Thanks,
Balazs

![screenshot from 2016-10-31 20 07 02](https://cloud.githubusercontent.com/assets/3719690/19867944/308a5e7c-9fa6-11e6-9275-541b4f2ec966.png)

**Comment by pabender** [comment]
That one I have not been able to figure out ( yet ) other than I know it is dependent on window width.

**Comment by dpharris** [comment]
I have wondered whether we should use a different windowing package.  I
faught with these kinds of issues but they defeated me :-(

David
