### ISSUE TITLE
Color / disable the "save changes" button

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#147]
Since #47 we have a "save changed" button in the CDI window in the bottom. We should give visual indication to the user whether there is anything to save there. This visual indication should be two-fold:
1) color the background orange like any other field that is changed.
2) make the button disabled in a way that the user cannot click it if there is nothing to save. Add tooltip text saying "nothing to save" when the user has not actually changed anything yet.

I believe we should do both, because the background coloring only works with the metal UI look&feel (#55) but the button disabled is implemented across all look&feels.

**Comment by atanisoft** [comment]
Perhaps also extend this enhancement to track the dirty state and have a pop-up to prompt the user "do you wish to save modifications" when they close the dialog.

**Comment by petecressman** [comment]
Fix pending in PR #161. Also change name to "Write All"

**Comment by balazsracz** [comment]
Fixed by #178.
