### ISSUE TITLE
JMRI/PanelPro' built-in GridConnect Hub echos packets on the TCP/IP side.  

### ISSUE THREAD

**Issue by RobertPHeller** [openlcb/OpenLCB_Java#148]

**Comment by RobertPHeller** [comment]
When starting a hub in PanelPro and then connecting a GC over Tcp/Ip, the new node goes into "endless" alias allocation, appearently because PanelPro is [incorrectly] sending the alias allocation messages back out the Tcp/Ip socket channel, causinf the new node  to think there is an alias conflict.

**Comment by bobjacobsen** [comment]
Believed to be fixed by JMRI/JMRI#11150 which is in [JMRI test release 5.1.2](https://www.jmri.org/releasenotes/jmri5.1.2.shtml)
