### ISSUE TITLE
JMRI/PanelPro fails to allocate an alias for itself when connecting to an LCC CAN bus

### ISSUE THREAD

**Issue by RobertPHeller** [openlcb/OpenLCB_Java#149]
JMRI/PanelPro, when joining an LCC CAN bus neglects to go through the complete alias allocation process, as specificed in the spec.: S-9.7.2.1 "Layout Command Control® (LCC) CAN Frame Transfer", section 6.2.1 "Reserving a Node ID Alias".  This causes problems for other nodes seeking to interogate the JMRI/PanelPro virtual node (eg getting simple node info or supported protocoles, etc.).

**Comment by bobjacobsen** [comment]
Not sure which version it first appeared, but this is now fixed. JMRI does the CID, RID, etc sequence now.
