### ISSUE TITLE
Track "configuration dirty" to control call to CdiPanel.runUpdateComplete()

### ISSUE THREAD

**Issue by atanisoft** [openlcb/OpenLCB_Java#150]
While it is useful for the CdiPanel to trigger runUpdateComplete() automatically on close, the code in runUpdateComplete() should only send the datagram if the config has in fact been updated and written to the node. This currently leads to the OpenMRN ConfigUpdateListener::apply_configuration method to be called even if the config hasn't been updated which could be considered an unintended behavior.

**Comment by petecressman** [comment]
Fix pending in PR #161

**Comment by balazsracz** [comment]
Fixed by #178
