### ISSUE TITLE
Sending eventid immediately from CDI panel

### ISSUE THREAD

**Issue by dpharris** [openlcb/OpenLCB_Java#188]
I would like to be able to send the eventid that I am configuring from the CDI panel.  Can we add a button to do that, or some equivalent action (double click, a keypress, mouse activated dropdown menu).  

Thanks.

**Comment by kiwi64ajs** [comment]
Yeah, that would be very handy when you’re try things out or tweaking things

**Comment by bobjacobsen** [comment]
@dpharris There is now a "Trigger" option under "More...".  Is that doing what you want? If so, can we close this?
