### ISSUE TITLE
LCC Hub IP address only shows localhost

### ISSUE THREAD

**Issue by bakerstu** [openlcb/OpenLCB_Java#207]
Verified in JMRI 5.0+Rc441642522 running under Ubuntu 20.04.

After starting an LCC Hub (LCC->Start Hub), a window pops open that shows the "Hub IP address", but only shows "127.0.1.1:12021". Actually, this is not even the correct "localhost" because that would be 127.0.0.1. I'm not sure where 127.0.1.1 is actually coming from.

It would be much more valuable for the user if the window listed (all of) the host IP address(s) and port numbers similar to what the WiThrottle Server window does.

I'm not sure if this logic is resides in this repo or in the JMRI repo.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/2278798/193427169-9d8c7000-8664-407c-9460-156cfc1ee1d3.png">

**Comment by bakerstu** [comment]
One more thing I noticed is that the title of the window is "OpenLCB" even though the connection type is LCC. This is otherwise fine, but it may confuse some users that don't know what OpenLCB is. Should it be changed it to "LCC/OpenLCB Hub Control"?

**Comment by dpharris** [comment]
I will have a look around and see if I can improve things.

David

**Comment by RobertPHeller** [comment]
At Sat, 01 Oct 2022 13:29:47 -0700 openlcb/OpenLCB_Java ***@***.***> wrote:

> 
> Verified in JMRI 5.0+Rc441642522 running under Ubuntu 20.04.
> 
> After starting an LCC Hub (LCC->Start Hub), a window pops open that shows the "Hub IP address", but only shows "127.0.1.1:12021". Actually, this is not even the correct "localhost" because that would be 127.0.0.1. I'm not sure where 127.0.1.1 is actually coming from.

I believe that all 127.0.0.0/8 addresses work for localhost and connect to the
loopback network device.

> 
> It would be much more valuable for the user if the window listed (all of) the host IP address(s) and port numbers similar to what the WiThrottle Server window does.
> 
> I'm not sure if this logic is resides in this repo or in the JMRI repo.
> 
> <img width="492" alt="image" src="https://user-images.githubusercontent.com/2278798/193427169-9d8c7000-8664-407c-9460-156cfc1ee1d3.png">
> 

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services

**Comment by balazsracz** [comment]
We should do the same thing as JMRI does for the withrottle window, which
lists all local interfaces with their IP addresses.

**Comment by bobjacobsen** [comment]
The JMRI code for WiThrottle is near line 100 in java/src/jmri/jmrit/withrottle//UserInterface.java

**Comment by dpharris** [comment]
Bob --

Thanks, this is helpful.

David

**Comment by bobjacobsen** [comment]
The JMRI code that displays the hub address is in java/src/jmri/jmrix/openlcb/swing/hub/HubPane.java and the title is set in java/src/jmri/jmrix/openlcb/swing/hub/HubAction.java

**Comment by icklesteve** [comment]
Hi @dpharris
I'm having a look at the Hub swing code in JMRI so can sort unless you're close?

I'm also thinking appending the connection / disconnection messages from the Hub into a scrollable list would be a nice mini update ;-)

Steve.

**Comment by dpharris** [comment]
Steve --

Go ahead.  I have pulled my horns in at the moment for other changes.

David

**Comment by icklesteve** [comment]
Hi @bakerstu 

There have been some tweaks in this area in JMRI 5.3.4
If you could confirm this now displays as expected?

Thanks, Steve.

**Comment by bobjacobsen** [comment]
Here's what it looks like now:

![image](https://user-images.githubusercontent.com/2774117/229351195-d2b62b2e-cc5e-4e82-aeb8-c510d620c49d.png)

**Comment by icklesteve** [comment]
See https://github.com/JMRI/JMRI/pull/11902 which adds the LinkLocal connection, missed on previous update.

**Comment by dpharris** [comment]
Should we include a line that indicates that it is advertised as "
openlcbcan.local."?

David

**Comment by icklesteve** [comment]
The Bonjour/Zeroconf is also documented at https://www.jmri.org/help/en/html/doc/Technical/Networking.shtml , see the Upstream Connections list.
