### ISSUE TITLE
ProtocolInformationReply messages can be incorrectly parsed if not 8 bytes

### ISSUE THREAD

**Issue by rm5248** [openlcb/OpenLCB_Java#210]
When sending a ProtocolSupportReply message over the LCC bus, if the payload is not 8 bytes long it is not parsed correctly([more information](https://groups.io/g/openlcb/topic/96448261)).

In JMRI, the following is displayed in the traffic monitor when only one byte of data is sent back:
```
[[196685f7] 02 F7 D4 18 20 00 00 00]  R: 02.01.57.10.05.80 - 02.01.12.FE.6C.0F ProtocolSupportReply with payload D4 18 20 00 00 00
[[19668a5d] 02 F7 80               ]  R: 04.00.32.40.50.01 - 02.01.12.FE.6C.0F ProtocolSupportReply with payload 00 00 00 00 00 80
```

It appears that when the data is parsed in OpenLCB, it assumes that the [data is a long](https://github.com/openlcb/OpenLCB_Java/blob/d636b2762adfb4abeb2dc99301eef204b917c631/src/org/openlcb/ProtocolIdentificationReplyMessage.java#L26).  It seems that because there is not enough data to parse, the fact that it is assuming a 6-byte protocol support causes the resulting output to be incorrect.

**Comment by bobjacobsen** [comment]
The parsing happens at [can.MessageBuilder#265](https://github.com/openlcb/OpenLCB_Java/blob/d636b2762adfb4abeb2dc99301eef204b917c631/src/org/openlcb/can/MessageBuilder.java#L265). One way to fix this would be to add and use a `paddedDataAsLong` method in CanFrame that handles the necessary padding.
