### ISSUE TITLE
Reload config after factory reset

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#232]
Since #227 we have a factory reset in the More... menu in the CDI.
After the factory reset completes, we should reload the CDI values. This would also give visual confirmation to the user that something did happen.

The tricky business is *when* to do it. The node might need a small amount of time to actually perform the factory reset. This might involve erasing flash for example, during which the node is often not responsive. It might reboot the node. The node might send out a node initialization complete. It might send out a bunch of event identification messages. These are good hints that the reset is complete.

My recommendation is this:
- Install a message decoder
- Start a timer for 3 seconds
- if there is a node initialization complete message coming in, or any producer/consumer identified, cancel the timer
When the timer is expired or cancelled, trigger the action of "refresh all" button.

**Comment by dpharris** [comment]
Resolved with updates.
