### ISSUE TITLE
Can we update the OpenLCB_Java library to Java 11?

### ISSUE THREAD

**Issue by bobjacobsen** [openlcb/OpenLCB_Java#273]
This project is currently built against Java 8.

There are several nice features in Java 11, most recently the `String.strip()` method would have been good do use. 

Can we update the required source level for building to Java 11?

If I don't hear objections in the next couple weeks, I'll go ahead and do this.

**Comment by balazsracz** [comment]
We have to verify that building android applications is possible with a
java 11 compiler. This is not obvious.

**Comment by bobjacobsen** [comment]
>We have to verify that building android applications is possible with a java 11 compiler. This is not obvious.

Good point. How far back does this need to go?  [This page](https://developer.android.com/build/jdks) makes it sound like Java 11 goes back at least as far as Android 12.  

Is there a way to do an Android build in CI to make sure we don't break this?

**Comment by bobjacobsen** [comment]
Wow.  Android 4.1 is from 12 years ago! 

Well, I guess that answers the question of whether we can update this to Java 11:  We can't.
