### ISSUE TITLE
Publish in Maven Central

### ISSUE THREAD

**Issue by rhwood** [openlcb/OpenLCB_Java#32]
It would be helpful, for those projects that track dependencies using maven or other dependency management tools, if the JARs for this project could be published in [Maven Central](http://search.maven.org).

**Comment by balazsracz** [comment]
@rhwood :
If we go with maven central, what defines who is allowed to publish a new binary releases of the code? Who represents the "authority" of the OpenLCB team?

OpenLCB is a very loosely and informally organized group and such questions of authority always create difficulties and tensions in moving forward with certain decisions.

**Comment by rhwood** [comment]
> If we go with maven central, what defines who is allowed to publish a new binary releases of the code? Who represents the "authority" of the OpenLCB team?

Once an organization is created in maven central, the creator of that organization is its owner and can take further action to get others added to maven central to be allowed to publish on behalf of this project.

> OpenLCB is a very loosely and informally organized group and such questions of authority always create difficulties and tensions in moving forward with certain decisions.

Whoever creates the organization within maven central can add anyone else (who has an account on maven central) to the list of people allowed to make a release. I'd suggest that anyone who can make a release in this repo now should be allowed to make that release.

**Comment by balazsracz** [comment]
The central repository now has openlcb 0.7.10 release:
http://search.maven.org/#search%7Cga%7C1%7Copenlcb
