### ISSUE TITLE
Retry load datagram errors while fetching the CDI

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#42]
If one of the datagrams for loading the CDI fails (for whaever reason, timeout, etc), we abort the load and return a partial XML for parsing -- which will always fail.
We should re-try the datagram load a few times before giving up.

**Comment by balazsracz** [comment]
this is in the file CdiMemConfigReader.java

**Comment by dpharris** [comment]
I do not know how to reissue the datagram.  Here is the fail code:
     MemoryConfigurationService.McsReadHandler memo =
            new MemoryConfigurationService.McsReadHandler() {
                @Override
                public void handleFailure(int code) {
                    logger.warning("Error reading CDI: " + Integer.toHexString(code));
                    done();
                    // TODO: 5/2/16 proxy error messages to the caller.
                    // don't do next request
                }

**Comment by bobjacobsen** [comment]
See PR #228
