### ISSUE TITLE
Import to GitHub improperly failed to attribute authorship

### ISSUE THREAD

**Issue by bobjacobsen** [openlcb/OpenLCB_Java#78]
It looks like this GitHub repository was made from the [OpenLCB SourceForge.net SVN](https://sourceforge.net/p/openlcb/svn/HEAD/tree/).

Unfortunately, whoever did this didn't properly import the authorship attributions, and the connection between the original SVN-resident commits and their authorship on GitHub was broken. (This is normally done with --author on [git-svn](https://git-scm.com/docs/git-svn) or --authors on [svn2git](https://github.com/nirvdrum/svn2git#authors); see the [JMRI author conversation file](https://github.com/JMRI/contributors/blob/master/authors-transform.txt) for an example)

For more discussion of why this is a problem, including sample commits and links to the licensing terms in the SourceForge repository, please see the related Issue openlcb/documents#4.

In my case, all the work I authored in multiple commits over several years is now attributed to "jacobsen", who is most definitely _NOT_ me. I'm "bobjacobsen" on GitHub. The "jacobsen" account is somebody different!

The attributions in this repository must be fixed promptly.

**Comment by balazsracz** [comment]
This is now complete.

$ git log --format='%an %ae' | sed 's/ [^ ]*@/ x@/' | sort | uniq -c | sort -n
      5 David Harris x@telus.net
     29 Randall Wood x@alexandriasoftware.com
     42 Paul Bender x@acm.org
    345 Balazs Racz x@gmail.com
    350 Bob Jacobsen x@mac.com

thanks Bob for bringing this to our attention.

The previous master is archived at a branch called "oldmaster" for now. After a while we could delete and garbage collect it, but I propose a holding period of about a year or so.

**Comment by balazsracz** [comment]
Also added Licensing page.
